# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a base Python image with a version higher than 3.10
FROM python:3.10-slim as base

# Set the working directory
WORKDIR /app

# Copy the requirements and source files
COPY pyproject.toml ./
COPY src/ ./src/

# Install build tools and uv package manager
RUN pip install --no-cache-dir uv

# Copy the .env file (ensure it's in the build context)
COPY .env ./

# Install the project dependencies using uv
RUN uv sync --frozen --no-install-project --no-dev --no-editable

# Set the environment variable for uv
ENV UV_LINK_MODE=copy

# Run the MCP server
CMD ["uv", "run", "--with", "fastmcp", "--with", "httpx", "--with", "netCDF4", "--with", "numpy", "--with", "pandas", "--with", "pydantic", "--with", "python-dotenv", "--with", "xarray", "fastmcp", "run", "src/knmi_weather_mcp/server.py"]
